#!/usr/bin/env bash
# onboarding-check.sh — verify a fresh developer's local environment is
# actually configured to match the committed AI-native guardrails.
#
# Runs on demand or as part of a project's `/onboarding-check` slash
# command. Reports per-check pass/fail with a summary. Exit code:
#   0  all checks pass
#   1  at least one check failed — the developer's setup needs attention
#
# This is the DEVELOPER-SIDE analog of ai-native-verify. ai-native-verify
# checks that the REPO is correctly configured; onboarding-check confirms
# the developer's CLONE is activated to match.

set -euo pipefail

BOLD=$'\033[1m'
GREEN=$'\033[32m'
YELLOW=$'\033[33m'
RED=$'\033[31m'
RESET=$'\033[0m'
[[ -t 1 ]] || { BOLD=""; GREEN=""; YELLOW=""; RED=""; RESET=""; }

PASS=0
FAIL=0
FAIL_NAMES=()

pass_check() {
  (( ++PASS ))
  printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"
}

fail_check() {
  (( ++FAIL ))
  FAIL_NAMES+=("$1")
  printf '  %s✗%s %s\n' "$RED" "$RESET" "$1"
  [[ -n ${2:-} ]] && printf '      %s\n' "$2"
}

section() {
  printf '\n%s%s%s\n' "$BOLD" "$1" "$RESET"
}

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || {
  printf '%serror:%s not inside a git repository\n' "$RED" "$RESET" >&2
  exit 1
}
cd "$REPO_ROOT"

# ─────────────────────────────────────────────────────────────────────────
section "Repository governance"
# ─────────────────────────────────────────────────────────────────────────

if [[ -f AGENTS.md ]]; then
  pass_check "AGENTS.md present at repo root"
else
  fail_check "AGENTS.md missing" "the target repo should have an AGENTS.md — see rubric §Part 1 D01"
fi

if [[ -L CLAUDE.md ]] && [[ "$(readlink CLAUDE.md)" == "AGENTS.md" ]]; then
  pass_check "CLAUDE.md symlinked to AGENTS.md"
elif [[ -f CLAUDE.md ]]; then
  fail_check "CLAUDE.md is a regular file, not a symlink" "rm CLAUDE.md && ln -s AGENTS.md CLAUDE.md"
else
  fail_check "CLAUDE.md missing" "ln -s AGENTS.md CLAUDE.md"
fi

if [[ -f .claude/settings.json ]]; then
  pass_check ".claude/settings.json committed (policy-as-code active on session start)"
else
  fail_check ".claude/settings.json missing" "governance is advisory-only without it"
fi

# ─────────────────────────────────────────────────────────────────────────
section "Developer environment"
# ─────────────────────────────────────────────────────────────────────────

if command -v git >/dev/null 2>&1; then
  pass_check "git installed ($(git --version))"
else
  fail_check "git missing" "install git — no clone workflow is possible without it"
fi

if command -v pre-commit >/dev/null 2>&1; then
  pass_check "pre-commit installed ($(pre-commit --version))"
else
  fail_check "pre-commit not installed" "run ./scripts/setup-precommit.sh"
fi

# ─────────────────────────────────────────────────────────────────────────
section "Pre-commit hook activation"
# ─────────────────────────────────────────────────────────────────────────

# The committed config exists → hooks should be installed locally.
if [[ -f .pre-commit-config.yaml || -f .pre-commit-config.yml ]]; then
  if [[ -f .git/hooks/pre-commit ]] \
     && grep -q "generated by pre-commit" .git/hooks/pre-commit 2>/dev/null; then
    pass_check "pre-commit hook active in .git/hooks/pre-commit"
  else
    fail_check "pre-commit hook not installed" \
      "the config is committed but not activated locally — run ./scripts/setup-precommit.sh"
  fi

  # Check commit-msg hook if the config has commit-msg stage hooks.
  if grep -qE 'stages:.*\bcommit-msg\b' .pre-commit-config.y*ml 2>/dev/null; then
    if [[ -f .git/hooks/commit-msg ]] \
       && grep -q "generated by pre-commit" .git/hooks/commit-msg 2>/dev/null; then
      pass_check "commit-msg hook active (Conventional Commits enforcement)"
    else
      fail_check "commit-msg hook not installed" \
        "run 'pre-commit install --hook-type commit-msg'"
    fi
  fi
else
  fail_check ".pre-commit-config.yaml missing" \
    "the repo has no committed pre-commit config — check with the team"
fi

# ─────────────────────────────────────────────────────────────────────────
section "Commit template"
# ─────────────────────────────────────────────────────────────────────────

if [[ -f .gitmessage ]]; then
  template=$(git config --get commit.template 2>/dev/null || true)
  if [[ "$template" == ".gitmessage" ]] || [[ "$template" == "$REPO_ROOT/.gitmessage" ]]; then
    pass_check "commit.template configured to .gitmessage"
  else
    fail_check "commit.template not configured" \
      "run 'git config commit.template .gitmessage' — the shared Conventional Commits template opens on 'git commit' with no -m"
  fi
fi

# ─────────────────────────────────────────────────────────────────────────
section "MCP servers (optional but recommended)"
# ─────────────────────────────────────────────────────────────────────────

if [[ -f .mcp.json ]]; then
  # Very light check — just JSON validity. Deeper checks (are the servers
  # actually reachable, are the tokens set) go project-specific.
  if command -v python3 >/dev/null 2>&1 \
     && python3 -c "import json,sys; json.load(open('.mcp.json'))" 2>/dev/null; then
    pass_check ".mcp.json valid JSON"
    # Warn if any env-var references look unresolved.
    if grep -oE '\${[A-Z_][A-Z_0-9]*}' .mcp.json 2>/dev/null | sort -u | while read -r var; do
      name=${var#\${}
      name=${name%\}}
      if [[ -z "${!name:-}" ]]; then
        printf '      %s(env var %s referenced in .mcp.json is unset)%s\n' "$YELLOW" "$name" "$RESET"
      fi
    done; then :; fi
  else
    fail_check ".mcp.json invalid JSON" "fix syntax before starting a Claude Code session"
  fi
fi

# ─────────────────────────────────────────────────────────────────────────
# Report
# ─────────────────────────────────────────────────────────────────────────

printf '\n%sresults%s  ' "$BOLD" "$RESET"
if (( FAIL == 0 )); then
  printf '%s%d passed%s — environment ready\n' "$GREEN" "$PASS" "$RESET"
  exit 0
fi
printf '%s%d passed%s, %s%d failed%s\n' "$GREEN" "$PASS" "$RESET" "$RED" "$FAIL" "$RESET"
printf 'failed:\n'
for n in "${FAIL_NAMES[@]}"; do printf '  - %s\n' "$n"; done
printf '\nFix the failures above and re-run. Most are resolved by running:\n'
printf '  ./scripts/setup-precommit.sh\n'
exit 1
